package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/fulmenhq/refbolt/internal/config"
	"github.com/fulmenhq/refbolt/internal/provider"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var (
	initTopics []string
	initAll    bool
	initOutput string
	initForce  bool
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a starter providers.yaml from the built-in catalog",
	Long: `Generate a providers.yaml config file from refbolt's built-in provider catalog.

Select topics to include, or use --all for the full catalog.
Output goes to stdout by default (pipe to file), or use --output.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if !initAll && len(initTopics) == 0 {
			// Interactive mode placeholder — for now require flags.
			fmt.Fprintln(os.Stderr, "Available topics (use --topic or --all):")
			catalog, err := config.CatalogTopics()
			if err != nil {
				return err
			}
			for _, t := range catalog {
				enabledCount := 0
				for _, p := range t.Providers {
					if p.IsEnabled() {
						enabledCount++
					}
				}
				fmt.Fprintf(os.Stderr, "  %s (%d providers)\n", t.Slug, enabledCount)
			}
			return fmt.Errorf("no topics selected; use --topic <slug> or --all")
		}

		catalog, err := config.CatalogTopics()
		if err != nil {
			return err
		}

		// Filter to selected topics.
		var selected []config.Topic
		if initAll {
			selected = catalog
		} else {
			topicSet := make(map[string]bool)
			for _, t := range initTopics {
				topicSet[t] = true
			}
			for _, t := range catalog {
				if topicSet[t.Slug] {
					selected = append(selected, t)
					delete(topicSet, t.Slug)
				}
			}
			for slug := range topicSet {
				return fmt.Errorf("unknown topic: %q", slug)
			}
		}

		// Build the output config structure.
		output := buildInitConfig(selected)

		yamlBytes, err := yaml.Marshal(output)
		if err != nil {
			return fmt.Errorf("marshaling config: %w", err)
		}

		header := fmt.Sprintf("# refbolt provider configuration\n# Generated by: refbolt init (v%s)\n# Edit this file to enable/disable providers.\n# Validate with: refbolt validate\n", appVersion)

		yamlWithComments := injectCredentialComments(string(yamlBytes), selected)
		content := []byte(header + yamlWithComments)

		// Write to file or stdout.
		if initOutput != "" {
			if !initForce {
				if _, err := os.Stat(initOutput); err == nil {
					return fmt.Errorf("%s already exists; use --force to overwrite", initOutput)
				}
			}
			if err := os.WriteFile(initOutput, content, 0o644); err != nil {
				return fmt.Errorf("writing config: %w", err)
			}
			fmt.Fprintf(os.Stderr, "Config written to %s\n", initOutput)
		} else {
			// stdout — YAML only, no human text.
			os.Stdout.Write(content)
		}

		// Credential hints to stderr.
		creds := config.CredentialRequirements(selected)
		if len(creds) > 0 {
			fmt.Fprintln(os.Stderr)
			fmt.Fprintln(os.Stderr, "Heads up: some providers need API keys for reliable syncs:")
			for _, c := range creds {
				fmt.Fprintf(os.Stderr, "  %-15s — %s (%s)\n", c.EnvVar, joinSlugs(c.Providers), c.Reason)
			}
			fmt.Fprintln(os.Stderr)
			fmt.Fprintln(os.Stderr, "See: docs/development.md → Environment Variables")
		}

		return nil
	},
}

// initConfigOutput is the serializable config structure for init output.
type initConfigOutput struct {
	ArchiveRoot string            `yaml:"archive_root"`
	Topics      []initTopicOutput `yaml:"topics"`
}

type initTopicOutput struct {
	Slug        string               `yaml:"slug"`
	Name        string               `yaml:"name,omitempty"`
	Description string               `yaml:"description,omitempty"`
	Providers   []initProviderOutput `yaml:"providers"`
}

type initProviderOutput struct {
	Slug           string   `yaml:"slug"`
	Name           string   `yaml:"name"`
	BaseURL        string   `yaml:"base_url"`
	FetchStrategy  string   `yaml:"fetch_strategy"`
	LLMSTxtURL     string   `yaml:"llms_txt_url,omitempty"`
	OpenAPIURL     string   `yaml:"openapi_url,omitempty"`
	GitHubRepo     string   `yaml:"github_repo,omitempty"`
	GitHubDocsPath string   `yaml:"github_docs_path,omitempty"`
	GitHubBranch   string   `yaml:"github_branch,omitempty"`
	AuthEnvVar     string   `yaml:"auth_env_var,omitempty"`
	FetchTimeout   string   `yaml:"fetch_timeout,omitempty"`
	Paths          []string `yaml:"paths,omitempty"`
}

func buildInitConfig(topics []config.Topic) initConfigOutput {
	out := initConfigOutput{
		ArchiveRoot: "./archive",
	}
	for _, t := range topics {
		topicOut := initTopicOutput{
			Slug: t.Slug,
		}
		for _, p := range t.Providers {
			po := initProviderOutput{
				Slug:           p.Slug,
				Name:           p.Name,
				BaseURL:        p.BaseURL,
				FetchStrategy:  string(p.FetchStrategy),
				LLMSTxtURL:     p.LLMSTxtURL,
				OpenAPIURL:     p.OpenAPIURL,
				GitHubRepo:     p.GitHubRepo,
				GitHubDocsPath: p.GitHubDocsPath,
				GitHubBranch:   p.GitHubBranch,
				AuthEnvVar:     p.AuthEnvVar,
				Paths:          p.Paths,
			}
			if p.FetchTimeout > 0 {
				po.FetchTimeout = p.FetchTimeout.String()
			}
			topicOut.Providers = append(topicOut.Providers, po)
		}
		out.Topics = append(out.Topics, topicOut)
	}
	return out
}

// injectCredentialComments adds inline YAML comments before providers that
// need API keys. Since Go's yaml.v3 Marshal doesn't support comments,
// we post-process the YAML string.
func injectCredentialComments(yamlStr string, topics []config.Topic) string {
	for _, t := range topics {
		for _, p := range t.Providers {
			var comment string
			if p.FetchStrategy == provider.StrategyJina {
				comment = fmt.Sprintf("      # %s — HTML only, fetched via Jina Reader.\n      # Set JINA_API_KEY for reliable syncs (anonymous access is rate-limited).\n", p.Name)
			} else if p.AuthEnvVar == "GITHUB_TOKEN" {
				comment = fmt.Sprintf("      # %s — GitHub source. Set GITHUB_TOKEN to avoid rate limits.\n", p.Name)
			}
			if comment != "" {
				target := fmt.Sprintf("      - slug: %s\n", p.Slug)
				yamlStr = strings.Replace(yamlStr, target, comment+target, 1)
			}
		}
	}
	return yamlStr
}

func joinSlugs(slugs []string) string {
	return strings.Join(slugs, ", ")
}

func init() {
	initCmd.Flags().StringArrayVar(&initTopics, "topic", nil, "Topic(s) to include (repeatable)")
	initCmd.Flags().BoolVar(&initAll, "all", false, "Include all topics from catalog")
	initCmd.Flags().StringVar(&initOutput, "output", "", "Write config to file (default: stdout)")
	initCmd.Flags().BoolVar(&initForce, "force", false, "Overwrite existing output file")
	rootCmd.AddCommand(initCmd)
}
