package cmd

import (
	"fmt"
	"os"

	"github.com/fulmenhq/refbolt/internal/config"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var (
	initTopics []string
	initAll    bool
	initOutput string
	initForce  bool
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a starter providers.yaml from the built-in catalog",
	Long: `Generate a providers.yaml config file from refbolt's built-in provider catalog.

Select topics to include, or use --all for the full catalog.
Output goes to stdout by default (pipe to file), or use --output.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if !initAll && len(initTopics) == 0 {
			// Interactive mode placeholder — for now require flags.
			fmt.Fprintln(os.Stderr, "Available topics (use --topic or --all):")
			catalog, err := config.CatalogTopics()
			if err != nil {
				return err
			}
			for _, t := range catalog {
				enabledCount := 0
				for _, p := range t.Providers {
					if p.IsEnabled() {
						enabledCount++
					}
				}
				fmt.Fprintf(os.Stderr, "  %s (%d providers)\n", t.Slug, enabledCount)
			}
			return fmt.Errorf("no topics selected; use --topic <slug> or --all")
		}

		catalog, err := config.CatalogTopics()
		if err != nil {
			return err
		}

		// Filter to selected topics.
		var selected []config.Topic
		if initAll {
			selected = catalog
		} else {
			topicSet := make(map[string]bool)
			for _, t := range initTopics {
				topicSet[t] = true
			}
			for _, t := range catalog {
				if topicSet[t.Slug] {
					selected = append(selected, t)
					delete(topicSet, t.Slug)
				}
			}
			for slug := range topicSet {
				return fmt.Errorf("unknown topic: %q", slug)
			}
		}

		// Build the output config structure.
		output := buildInitConfig(selected)

		yamlBytes, err := yaml.Marshal(output)
		if err != nil {
			return fmt.Errorf("marshaling config: %w", err)
		}

		header := fmt.Sprintf("# refbolt provider configuration\n# Generated by: refbolt init (v%s)\n# Edit this file to enable/disable providers.\n# Validate with: refbolt validate\n", appVersion)

		content := []byte(header + string(yamlBytes))

		// Write to file or stdout.
		if initOutput != "" {
			if !initForce {
				if _, err := os.Stat(initOutput); err == nil {
					return fmt.Errorf("%s already exists; use --force to overwrite", initOutput)
				}
			}
			if err := os.WriteFile(initOutput, content, 0o644); err != nil {
				return fmt.Errorf("writing config: %w", err)
			}
			fmt.Fprintf(os.Stderr, "Config written to %s\n", initOutput)
		} else {
			// stdout — YAML only, no human text.
			os.Stdout.Write(content)
		}

		return nil
	},
}

// initConfigOutput is the serializable config structure for init output.
type initConfigOutput struct {
	ArchiveRoot string            `yaml:"archive_root"`
	Topics      []initTopicOutput `yaml:"topics"`
}

type initTopicOutput struct {
	Slug        string               `yaml:"slug"`
	Name        string               `yaml:"name,omitempty"`
	Description string               `yaml:"description,omitempty"`
	Providers   []initProviderOutput `yaml:"providers"`
}

type initProviderOutput struct {
	Slug           string   `yaml:"slug"`
	Name           string   `yaml:"name"`
	BaseURL        string   `yaml:"base_url"`
	FetchStrategy  string   `yaml:"fetch_strategy"`
	LLMSTxtURL     string   `yaml:"llms_txt_url,omitempty"`
	OpenAPIURL     string   `yaml:"openapi_url,omitempty"`
	GitHubRepo     string   `yaml:"github_repo,omitempty"`
	GitHubDocsPath string   `yaml:"github_docs_path,omitempty"`
	GitHubBranch   string   `yaml:"github_branch,omitempty"`
	AuthEnvVar     string   `yaml:"auth_env_var,omitempty"`
	FetchTimeout   string   `yaml:"fetch_timeout,omitempty"`
	Paths          []string `yaml:"paths,omitempty"`
}

func buildInitConfig(topics []config.Topic) initConfigOutput {
	out := initConfigOutput{
		ArchiveRoot: "./archive",
	}
	for _, t := range topics {
		topicOut := initTopicOutput{
			Slug: t.Slug,
		}
		for _, p := range t.Providers {
			po := initProviderOutput{
				Slug:           p.Slug,
				Name:           p.Name,
				BaseURL:        p.BaseURL,
				FetchStrategy:  string(p.FetchStrategy),
				LLMSTxtURL:     p.LLMSTxtURL,
				OpenAPIURL:     p.OpenAPIURL,
				GitHubRepo:     p.GitHubRepo,
				GitHubDocsPath: p.GitHubDocsPath,
				GitHubBranch:   p.GitHubBranch,
				AuthEnvVar:     p.AuthEnvVar,
				Paths:          p.Paths,
			}
			if p.FetchTimeout > 0 {
				po.FetchTimeout = p.FetchTimeout.String()
			}
			topicOut.Providers = append(topicOut.Providers, po)
		}
		out.Topics = append(out.Topics, topicOut)
	}
	return out
}

func init() {
	initCmd.Flags().StringArrayVar(&initTopics, "topic", nil, "Topic(s) to include (repeatable)")
	initCmd.Flags().BoolVar(&initAll, "all", false, "Include all topics from catalog")
	initCmd.Flags().StringVar(&initOutput, "output", "", "Write config to file (default: stdout)")
	initCmd.Flags().BoolVar(&initForce, "force", false, "Overwrite existing output file")
	rootCmd.AddCommand(initCmd)
}
