package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/fulmenhq/refbolt/internal/config"
	"github.com/fulmenhq/refbolt/internal/provider"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var (
	initTopics []string
	initAll    bool
	initOutput string
	initForce  bool
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a starter providers.yaml from the built-in catalog",
	Long: `Generate a providers.yaml config file from refbolt's built-in provider catalog.

Select topics to include, or use --all for the full catalog.
Output goes to stdout by default (pipe to file), or use --output.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if !initAll && len(initTopics) == 0 {
			// Interactive mode placeholder — for now require flags.
			fmt.Fprintln(os.Stderr, "Available topics (use --topic or --all):")
			catalog, err := config.CatalogTopics()
			if err != nil {
				return err
			}
			for _, t := range catalog {
				enabledCount := 0
				for _, p := range t.Providers {
					if p.IsEnabled() {
						enabledCount++
					}
				}
				fmt.Fprintf(os.Stderr, "  %s (%d %s)\n", t.Slug, enabledCount, pluralize(enabledCount, "provider", "providers"))
			}
			return fmt.Errorf("no topics selected; use --topic <slug> or --all")
		}

		catalog, err := config.CatalogTopics()
		if err != nil {
			return err
		}

		// Filter to selected topics.
		var selected []config.Topic
		if initAll {
			selected = catalog
		} else {
			topicSet := make(map[string]bool)
			for _, t := range initTopics {
				topicSet[t] = true
			}
			for _, t := range catalog {
				if topicSet[t.Slug] {
					selected = append(selected, t)
					delete(topicSet, t.Slug)
				}
			}
			for slug := range topicSet {
				return fmt.Errorf("unknown topic: %q", slug)
			}
		}

		// Build the output config structure.
		output := buildInitConfig(selected)

		yamlBytes, err := marshalInitConfig(output, selected)
		if err != nil {
			return fmt.Errorf("marshaling config: %w", err)
		}

		header := fmt.Sprintf("# refbolt provider configuration\n# Generated by: refbolt init (v%s)\n# Edit this file to enable/disable providers.\n# Validate with: refbolt validate\n", appVersion)

		content := append([]byte(header), yamlBytes...)

		// Write to file or stdout.
		if initOutput != "" {
			if !initForce {
				if _, err := os.Stat(initOutput); err == nil {
					return fmt.Errorf("%s already exists; use --force to overwrite", initOutput)
				}
			}
			if err := os.WriteFile(initOutput, content, 0o644); err != nil {
				return fmt.Errorf("writing config: %w", err)
			}
			fmt.Fprintf(os.Stderr, "Config written to %s\n", initOutput)
		} else {
			// stdout — YAML only, no human text.
			os.Stdout.Write(content)
		}

		// Credential hints to stderr. When the env var has a canonical
		// "get a key" URL, surface it inline so users don't have to
		// chase the README for it (FA-111 item #3).
		creds := config.CredentialRequirements(selected)
		if len(creds) > 0 {
			fmt.Fprintln(os.Stderr)
			fmt.Fprintln(os.Stderr, "Heads up: some providers need API keys for reliable syncs:")
			for _, c := range creds {
				url := config.CredentialURL(c.EnvVar)
				if url != "" {
					fmt.Fprintf(os.Stderr, "  %-15s — %s (%s). Get a key: %s\n",
						c.EnvVar, joinSlugs(c.Providers), c.Reason, url)
				} else {
					fmt.Fprintf(os.Stderr, "  %-15s — %s (%s)\n",
						c.EnvVar, joinSlugs(c.Providers), c.Reason)
				}
			}
			fmt.Fprintln(os.Stderr)
			fmt.Fprintln(os.Stderr, "See: docs/development.md → Environment Variables")
		}

		// Seed-flow hint for stdout mode: new users often miss that the
		// generated YAML is on stdout and expect a file (FA-111 item #6).
		// Only fire when no --output was specified — users who piped to
		// a file or used --output already know the pattern.
		if initOutput == "" {
			fmt.Fprintln(os.Stderr)
			fmt.Fprintln(os.Stderr, "Tip: to write this to a file, rerun with --output providers.yaml")
		}

		return nil
	},
}

// initConfigOutput is the serializable config structure for init output.
type initConfigOutput struct {
	ArchiveRoot string            `yaml:"archive_root"`
	Topics      []initTopicOutput `yaml:"topics"`
}

type initTopicOutput struct {
	Slug        string               `yaml:"slug"`
	Name        string               `yaml:"name,omitempty"`
	Description string               `yaml:"description,omitempty"`
	Providers   []initProviderOutput `yaml:"providers"`
}

type initProviderOutput struct {
	Slug           string   `yaml:"slug"`
	Name           string   `yaml:"name"`
	BaseURL        string   `yaml:"base_url"`
	FetchStrategy  string   `yaml:"fetch_strategy"`
	LLMSTxtURL     string   `yaml:"llms_txt_url,omitempty"`
	OpenAPIURL     string   `yaml:"openapi_url,omitempty"`
	GitHubRepo     string   `yaml:"github_repo,omitempty"`
	GitHubDocsPath string   `yaml:"github_docs_path,omitempty"`
	GitHubBranch   string   `yaml:"github_branch,omitempty"`
	AuthEnvVar     string   `yaml:"auth_env_var,omitempty"`
	FetchTimeout   string   `yaml:"fetch_timeout,omitempty"`
	Paths          []string `yaml:"paths,omitempty"`
}

func buildInitConfig(topics []config.Topic) initConfigOutput {
	out := initConfigOutput{
		ArchiveRoot: "./archive",
	}
	for _, t := range topics {
		topicOut := initTopicOutput{
			Slug: t.Slug,
		}
		for _, p := range t.Providers {
			po := initProviderOutput{
				Slug:           p.Slug,
				Name:           p.Name,
				BaseURL:        p.BaseURL,
				FetchStrategy:  string(p.FetchStrategy),
				LLMSTxtURL:     p.LLMSTxtURL,
				OpenAPIURL:     p.OpenAPIURL,
				GitHubRepo:     p.GitHubRepo,
				GitHubDocsPath: p.GitHubDocsPath,
				GitHubBranch:   p.GitHubBranch,
				AuthEnvVar:     p.AuthEnvVar,
				Paths:          p.Paths,
			}
			if p.FetchTimeout > 0 {
				// Emit in single-unit seconds ("90s") to satisfy the schema pattern,
				// which rejects compound forms like "1m30s" that time.Duration.String() produces.
				po.FetchTimeout = fmt.Sprintf("%ds", int64(p.FetchTimeout.Seconds()))
			}
			topicOut.Providers = append(topicOut.Providers, po)
		}
		out.Topics = append(out.Topics, topicOut)
	}
	return out
}

// marshalInitConfig serializes the init output and attaches credential-hint
// comments directly to the provider mapping nodes, so indentation is handled
// by the YAML encoder rather than string manipulation.
func marshalInitConfig(output initConfigOutput, topics []config.Topic) ([]byte, error) {
	// Collect per-slug head comments.
	comments := providerCommentIndex(topics)

	var root yaml.Node
	if err := root.Encode(output); err != nil {
		return nil, fmt.Errorf("encoding config: %w", err)
	}

	// root.Encode produces the top-level mapping directly (Kind=MappingNode),
	// not a DocumentNode wrapper.
	applyProviderComments(&root, comments)

	buf, err := yaml.Marshal(&root)
	if err != nil {
		return nil, fmt.Errorf("marshaling config: %w", err)
	}
	return buf, nil
}

// providerCommentIndex returns the head comment to attach to each provider
// slug. Providers without hints are absent from the map.
func providerCommentIndex(topics []config.Topic) map[string]string {
	out := make(map[string]string)
	for _, t := range topics {
		for _, p := range t.Providers {
			switch {
			case p.FetchStrategy == provider.StrategyJina:
				out[p.Slug] = fmt.Sprintf("%s — HTML only, fetched via Jina Reader.\nSet JINA_API_KEY for reliable syncs (anonymous access is rate-limited).", p.Name)
			case p.AuthEnvVar == "GITHUB_TOKEN":
				out[p.Slug] = fmt.Sprintf("%s — GitHub source. Set GITHUB_TOKEN to avoid rate limits.", p.Name)
			}
		}
	}
	return out
}

// applyProviderComments walks the config mapping and attaches HeadComment to
// each provider entry whose slug appears in comments.
func applyProviderComments(cfg *yaml.Node, comments map[string]string) {
	if cfg == nil || cfg.Kind != yaml.MappingNode {
		return
	}
	topicsNode := mappingValue(cfg, "topics")
	if topicsNode == nil || topicsNode.Kind != yaml.SequenceNode {
		return
	}
	for _, topic := range topicsNode.Content {
		providersNode := mappingValue(topic, "providers")
		if providersNode == nil || providersNode.Kind != yaml.SequenceNode {
			continue
		}
		for _, prov := range providersNode.Content {
			if prov.Kind != yaml.MappingNode {
				continue
			}
			slugNode := mappingValue(prov, "slug")
			if slugNode == nil {
				continue
			}
			if c, ok := comments[slugNode.Value]; ok {
				prov.HeadComment = c
			}
		}
	}
}

// mappingValue returns the value node associated with the given key in a
// mapping node, or nil if absent.
func mappingValue(m *yaml.Node, key string) *yaml.Node {
	if m == nil || m.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			return m.Content[i+1]
		}
	}
	return nil
}

func joinSlugs(slugs []string) string {
	return strings.Join(slugs, ", ")
}

func init() {
	initCmd.Flags().StringArrayVar(&initTopics, "topic", nil, "Topic(s) to include (repeatable)")
	initCmd.Flags().BoolVar(&initAll, "all", false, "Include all topics from catalog")
	initCmd.Flags().StringVar(&initOutput, "output", "", "Write config to file (default: stdout)")
	initCmd.Flags().BoolVar(&initForce, "force", false, "Overwrite existing output file")
	rootCmd.AddCommand(initCmd)
}
